{{- if .Values.collector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-mockado.fullname" . }}-collector
  labels:
    {{- include "backend-mockado.collector.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.collector.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.collector.service.type }}
  ports:
    - port: {{ .Values.collector.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.collector.service.ports.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.collector.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "backend-mockado.collector.selectorLabels" . | nindent 4 }}
{{- end }}