{{- if .Values.security.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "backend-mockado.collector.serviceAccountName" . }}
  labels:
    {{- include "backend-mockado.collector.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.security.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.security.serviceAccount.automountServiceAccountToken }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "backend-mockado.wiremock-loader.serviceAccountName" . }}
  labels:
    {{- include "backend-mockado.wiremock-loader.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.security.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.security.serviceAccount.automountServiceAccountToken }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "backend-mockado.wiremock.serviceAccountName" . }}
  labels:
    {{- include "backend-mockado.wiremock.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.security.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.security.serviceAccount.automountServiceAccountToken }}
{{- end }}