{{- if .Values.wiremock.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-mockado.fullname" . }}-wiremock
  labels:
    {{- include "backend-mockado.wiremock.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.wiremock.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.wiremock.service.type }}
  ports:
    - port: {{ .Values.wiremock.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "backend-mockado.wiremock.selectorLabels" . | nindent 4 }}
{{- end }}